# 7 Train And Datasets

# story for ML 
- Father => To train to his son to recognize cat/dog
- Images => Data - 100

# - Splitting the Data => ratio = 70 + 30

- Training => 70%

- Testing => 30%

- With train data => We need to train model(ML alg)

- Before training => Model donot know anything == 0 Know

- After training => Model know everything about the data

- Check accuracy => We need to the model

- Testing => 30% data we need to use for testing

- If accuracy => Good then deploy the model

- If accuracyb => Not good then retrain the model 

# Machine Learning Steps
### 1. Importing libraries
### 2. Loading the datasets
### 3. Data preparation
# 4. Splitting the dataset  => Train and Test Datasets
### 5. Creating the model (Algorithm)
### 6. Model training
### 7. Prediction

## 1 Types of Dataset in Machine learning
- There are mainly 3 types of datasets used in Machine learning
  1. Train dataset
  2. Test dataset
  3. Validation dataset
- Note
  1. Here validation dataset is an optional but training and test datasets are mandatory
  2. Dataset will be 100% , Training set 70% test set 30%

## 2 Train Dataset 
- Train dataset is used to train the models
- This is the part of dataset which is used to train the model
- Typically training set contains about 60-70% of the total dataset
- First setps is model should get train with training dataset durining training model learn the paramenters and underlying concepts from dataset

## 3 Test dataset 
- Test Dataset is used to test the model
- Once model training is done then we need to test the model with test dataset
- During testing the model we will understand about modele performance either good or not
- Size of test set is about 15-30% of total dataset

## 4 How to decide size of these 3 sets?
- There is no thumb rule about chossing the size of these sets, but according to the erperts '70-30' or 60-40 is a good size for train and test set respectively

## Creating array
- We can create an array and split that array

In [4]:
# Createing an array
import numpy as np

dataset=np.arange(10)

print(dataset)

[0 1 2 3 4 5 6 7 8 9]


## 6 train_test_split(p) function
- train_test_split(p) is a predefined function in sklearn.model_selection package
- We need to access this function from sklearn package
- By using this function we can split the dataset into train dataset and test dataset

In [59]:
## Creating an array and splitting dataset 

import numpy as np
from sklearn.model_selection import train_test_split

dataset=np.arange(10)

result=train_test_split(dataset)

print(dataset)
print()
print(result)
print()

result[0]
print()
result[1]

[0 1 2 3 4 5 6 7 8 9]

[array([0, 5, 1, 7, 6, 9, 8]), array([4, 3, 2])]




array([4, 3, 2])

In [58]:
from random import shuffle
a=[1,2,3,4,5,6,7,8,9]
shuffle(a)
print(a)

[1, 4, 3, 8, 7, 5, 2, 9, 6]


## train_test_split function can return single value (list having two arrays (train array and test array))

In [28]:
from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,101)

print(dataset)

result=train_test_split(dataset)
print()
print(result)
print(50*"*")
print(result[0])
print(50*"*")
print(result[1])

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

[array([ 84,  76,  39,  91,  36,  64,  99,  21,  10,  44,  26,  75,  17,
        63,  68,  25,  30,  78,  86,   6,  96,  12,  90,  65,  23,  32,
        53,  15,  37,  16,  74,  48,  88,   1,  51,  11,  40,  83,  14,
        18,  35,  95,  24,  50,  87,  41,  80,   3,  19,  89,  31,  55,
        62,  27,  29,  61,   2,  59,  42,  52,  67,  70,  71,  79,  34,
        38,  60,  92,  82,   9, 100,  93,  20,  33,  72]), array([43, 73,  7, 46, 69,  8, 97, 77, 28, 85, 56,  5, 49, 22, 57, 81, 13,
       66, 58,  4, 47, 98, 45, 94, 54])]
**************************************************
[ 84 

In [35]:
# Creating an array and splitting 
from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,11)
print(dataset)

x_train,x_test=train_test_split(dataset)
print()
print(x_train)
print()
print(x_test)

[ 1  2  3  4  5  6  7  8  9 10]

[9 7 3 2 1 6 8]

[ 4  5 10]


## train_test_split  function can return mutiple value (list having two arrays (train array and test array))


# train_test_split
- this function by default splitting the dataset into => 70:30
- Can i split the dataset into => 60:40  (yes)

In [1]:
# Creating an array and splitting 

from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,11)
print(dataset)

x_train,x_test=train_test_split(dataset,test_size=4)
print()
print(x_train,x_test)


[ 1  2  3  4  5  6  7  8  9 10]

[5 4 3 6 1 7] [ 2 10  8  9]


In [40]:
# Creating an array and splitting 

from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,11)
print(dataset)

x_train,x_test=train_test_split(dataset,train_size=6)
print()
print(x_train,x_test)

[ 1  2  3  4  5  6  7  8  9 10]

[ 9 10  6  7  2  1] [3 5 8 4]


In [41]:
# Creating an array and splitting 

from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,11)
print(dataset)

x_train,x_test=train_test_split(dataset,test_size=0.4)
print()
print(x_train,x_test)


[ 1  2  3  4  5  6  7  8  9 10]

[ 2 10  1  5  6  3] [4 8 9 7]


In [42]:
# Creating an array and splitting 

from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,11)
print(dataset)

x_train,x_test=train_test_split(dataset,train_size=0.6)
print()
print(x_train,x_test)

[ 1  2  3  4  5  6  7  8  9 10]

[4 2 6 1 7 3] [ 8  9  5 10]


In [43]:
# Creating an array and splitting  (we should not use this because its wasting the dataset)

from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,11)
print(dataset)

x_train,x_test=train_test_split(dataset,train_size=4,test_size=4)
print()
print(x_train,x_test)

[ 1  2  3  4  5  6  7  8  9 10]

[ 3 10  7  4] [6 9 1 5]


In [46]:
# Creating an array and splitting  (error)

from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,11)
print(dataset)

x_train,x_test=train_test_split(dataset,train_size=4,test_size=10)
print()
print(x_train,x_test)

[ 1  2  3  4  5  6  7  8  9 10]


ValueError: test_size=10 should be either positive and smaller than the number of samples 10 or a float in the (0, 1) range

# ValueError: test_size=10 should be either positive and smaller than the number of samples 10 or a float in the (0, 1) range

In [49]:
# Creating an array and splitting  
import numpy as np

dataset=np.arange(1,21)

print(dataset)  # output is in single row


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [54]:
# Creating an array and splitting  
import numpy as np

dataset=np.arange(1,21).reshape(2,10)

print(dataset)  # output is in two row

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [55]:
# Creating an array and splitting  
import numpy as np

dataset=np.arange(1,21).reshape(2,10).T

print(dataset)  

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]


In [69]:
# Creating an array and splitting  
import numpy as np

x=np.arange(1,21).reshape(2,10).T

print(x)

y=np.arange(10)
print()
print(y)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]

[0 1 2 3 4 5 6 7 8 9]


# X => called input == always in column format
# y => called output == always in row format

In [76]:
# Creating an array and splitting  
import numpy as np
from sklearn.model_selection import train_test_split

x=np.arange(1,21).reshape(2,10).T

print(x)

y=np.arange(10)
print()
print(y)
print(100*"*")

x_train,x_test=train_test_split(x)
print(x_train)
print()
print(x_test)

print(100*'*')
y_train,y_test=train_test_split(y)
print(y_train)
print()
print(y_test)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]

[0 1 2 3 4 5 6 7 8 9]
****************************************************************************************************
[[ 6 16]
 [10 20]
 [ 4 14]
 [ 5 15]
 [ 7 17]
 [ 8 18]
 [ 9 19]]

[[ 1 11]
 [ 2 12]
 [ 3 13]]
****************************************************************************************************
[5 3 1 2 6 8 0]

[9 4 7]


In [80]:
# Creating an array and splitting  (imp)
import numpy as np
from sklearn.model_selection import train_test_split

X=np.arange(1,21).reshape(2,10).T

print(X)

y=np.arange(10)
print()
print(y)
print(100*"*")

X_train,X_test,y_train,y_test=train_test_split(x,y)
print(X_train)
print()
print(X_test)
print()

print(100*"*")

print(y_train)
print()
print(y_test)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]

[0 1 2 3 4 5 6 7 8 9]
****************************************************************************************************
[[ 5 15]
 [ 1 11]
 [ 3 13]
 [ 9 19]
 [ 4 14]
 [ 8 18]
 [10 20]]

[[ 6 16]
 [ 2 12]
 [ 7 17]]

****************************************************************************************************
[4 0 2 8 3 7 9]

[5 1 6]


# The power of train_test_split
## - Can return single values (dataset)
## - Can return two values  (x_train,x_test)   
## - Can return four value  (x_train,x_test,y_train,y_test)

## 7 train_test_split(p,random_state=0) Function  
- train_test_split(p,random_state=0) is a predefined function in sklearn.model_selection package
- We need to access this function from sklearn package
- By using this function we can split the dataset into train dataset and test dataset
- We will get the same train and test dataset across different executions

In [88]:
# Creating an array and splitting  (one time splitting)

from sklearn.model_selection import train_test_split
import numpy as np

dataset=np.arange(1,21).reshape(2,10).T
print(dataset)
print()
print(50*'*')
X_train,X_test=train_test_split(dataset,random_state=0)
print(X_train)
print()
print(X_test)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]

**************************************************
[[10 20]
 [ 2 12]
 [ 7 17]
 [ 8 18]
 [ 4 14]
 [ 1 11]
 [ 6 16]]

[[ 3 13]
 [ 9 19]
 [ 5 15]]
